### ISSUE TITLE
Add Continuous Integration / Continuous Deployment

### ISSUE THREAD

**Issue by makotia** [lnsf/happynewyear2020#1]
CI/CD未経験者がVue CLI 3で作ったアプリをCircleCIでFirebaseにデプロイ - Qiita
https://qiita.com/takahiro-kato/items/a70ccbd79b3ff417e0f0#firebase%E3%81%AB%E3%83%93%E3%83%AB%E3%83%89

**Comment by lnsf** [comment]
https://happynewyear2020-e0a27.firebaseapp.com/ でホスティングされてます
